# Generated by Django 6.0.5 on 2026-05-11 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargaTMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='tms/')),
                ('total_registros', models.IntegerField(default=0)),
                ('total_filtrados', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga TMS',
                'verbose_name_plural': 'Cargas TMS',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pernoctacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.CharField(max_length=50)),
                ('id_viaje', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=200)),
                ('transporte_nombre', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=20)),
                ('patente_secundaria', models.CharField(blank=True, max_length=20)),
                ('conductor', models.CharField(max_length=200)),
                ('fecha_inicio_plan', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_plan', models.DateField(blank=True, null=True)),
                ('fecha_plan_descarga', models.DateField(blank=True, null=True)),
                ('direccion_descarga', models.CharField(blank=True, max_length=300)),
                ('operacion', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mail_enviado', models.BooleanField(default=False)),
                ('mail_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('lugar_pernoctacion', models.CharField(blank=True, max_length=300)),
                ('hora_eta', models.TimeField(blank=True, null=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('cumple_00h', models.BooleanField(blank=True, null=True)),
                ('extension_horaria', models.BooleanField(default=False)),
                ('observaciones_primera', models.TextField(blank=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('cumple_8h', models.BooleanField(blank=True, null=True)),
                ('horas_totales', models.DurationField(blank=True, null=True)),
                ('observaciones_segunda', models.TextField(blank=True)),
                ('sin_senal', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado por Transporte'), ('VALIDADO_1', 'Validado Turno Noche'), ('VALIDADO_2', 'Validado 8 Horas'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cargatms')),
                ('validado_primera_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_primera', to=settings.AUTH_USER_MODEL)),
                ('validado_segunda_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_segunda', to=settings.AUTH_USER_MODEL)),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transporte')),
            ],
            options={
                'verbose_name': 'Pernoctación',
                'verbose_name_plural': 'Pernoctaciones',
                'ordering': ['-fecha_registro', 'transporte_nombre'],
            },
        ),
    ]
